core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin-god/", admin.site.urls),
    path("", include("pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.PropiedadListView.as_view(), name="propiedades"),
    path("<int:pk>", views.PropiedadDetailView.as_view(), name="detalles"),
    path("contacto/", views.ContactoView.as_view(), name="contacto"),
]

pages/models.py
import uuid

from django.db import models
from django.urls import reverse

# Create your models here.


class Propiedad(models.Model):
    precio = models.IntegerField(verbose_name="Precio")
    dolares = models.BooleanField(verbose_name="Dolares")
    direccion = models.CharField(max_length=100, verbose_name="Dirección")
    numero_direccion = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Número de Dirección",
    )
    categoria = models.CharField(
        max_length=10,
        choices=[("Alquiler", "Alquiler"), ("Venta", "Venta")],
        verbose_name="Categoría",
    )
    nombre = models.CharField(max_length=50, verbose_name="Nombre")
    apellido = models.CharField(max_length=50, verbose_name="Apellido")
    correo = models.CharField(max_length=100, verbose_name="Dirección Electrónica")
    telefono = models.CharField(max_length=50, verbose_name="Número Telefónico")
    metros_cuadrados = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Metros Cuadrados",
    )
    habitaciones = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Habitaciones",
    )
    ambientes = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Ambientes",
    )
    baños = models.IntegerField(
        blank=True,
        null=True,
        verbose_name="Baños",
    )
    niños = models.CharField(
        blank=True,
        null=True,
        max_length=2,
        choices=[("Si", "Si"), ("No", "No")],
        verbose_name="Niños",
    )
    mascotas = models.CharField(
        blank=True,
        null=True,
        max_length=2,
        choices=[("Si", "Si"), ("No", "No")],
        verbose_name="Mascotas",
    )
    garage = models.IntegerField(
        blank=True, null=True, verbose_name="Espacio del Garage"
    )
    duracion_contrato = models.CharField(
        max_length=20, blank=True, null=True, verbose_name="Duración del Contrato"
    )
    expensas = models.IntegerField(blank=True, null=True, verbose_name="Expensas")
    antiguedad = models.IntegerField(
        blank=True, null=True, verbose_name="Antigüedad de la Construcción"
    )
    info_extra = models.TextField(blank=True, null=True, verbose_name="Información extra")
    destacado = models.BooleanField(verbose_name="Destacado")

    class Meta:
        verbose_name_plural = "Propiedades"

    def get_absolute_url(self):
        return reverse("detalles", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.nombre} {self.apellido}"


class Imagen(models.Model):
    propiedad = models.ForeignKey(Propiedad, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="imagenes/")

    class Meta:
        verbose_name_plural = "Imagenes"

    def __str__(self):
        return f"{self.propiedad.direccion} ({self.propiedad.nombre} {self.propiedad.apellido})"

pages/forms.py
from django import forms
from django.core.mail import send_mail
from .models import Propiedad, Imagen

# -------------------------


class PropiedadForm(forms.ModelForm):
    class Meta:
        model = Propiedad
        fields = "__all__"


class ImagenForm(forms.ModelForm):
    imagen = forms.ImageField(
        label="Imagen",
        widget=forms.ClearableFileInput(attrs={"allow_multiple_selected": True}),
    )

    class Meta:
        model = Imagen
        fields = ("imagen",)

pages/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, reverse
from django.views import generic
from django.http import HttpResponseRedirect

from .forms import PropiedadForm, ImagenForm
from .models import Propiedad, Imagen

# Create your views here.


class PropiedadListView(generic.ListView):
    model = Propiedad
    template_name = "pages/propiedades.html"
    context_object_name = "propiedades"
    ordering = ["-destacado"]

    def get_queryset(self):
        queryset = super().get_queryset()

        categoria = self.request.GET.get('categoria')
        if categoria:
            queryset = queryset.filter(categoria=categoria)
        
        return queryset


class PropiedadDetailView(generic.DetailView):
    model = Propiedad
    template_name = "pages/detalles.html"


class ContactoView(generic.TemplateView):
    template_name = "pages/contacto.html"

templates/_base.html
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Wynand</title>
  <link rel="apple-touch-icon" sizes="180x180" href={% static "icons/apple-touch-icon.png" %}>
  <link rel="icon" type="image/png" sizes="32x32" href={% static "icons/favicon-32x32.png" %}>
  <link rel="icon" type="image/png" sizes="16x16" href={% static "icons/favicon-16x16.png" %}>
  <link rel="manifest" href={% static "icons/site.webmanifest" %}>
  {% bootstrap_css %}
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body class="d-flex flex-column min-vh-100">
  <div class="navbar-bg fixed-top">
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand px-2" href="{% url 'propiedades' %}">Wynand</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span>{% bs_icon 'list' %}</span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link px-2" href="{% url 'propiedades' %}">Propiedades</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-2" href="{% url 'contacto' %}">Contacto</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
  {% block content %}{% endblock content %}
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 mt-auto">
    <div class="container d-flex flex-wrap justify-content-evenly">
      <div class="col-md-4 d-flex align-items-center">
        <span class="text-muted">© 2023 Wynandgroup. All rights reserved.</span>
      </div>
      <div class="col-md-4 d-flex align-items-center">
        <a class="text-muted" href="mailto:wynandgroup@gmail.com" target="_blank">{% bs_icon 'envelope-at' %}
          wynandgroup@gmail.com</a>
      </div>
    </div>
  </footer>
  {% bootstrap_javascript %}
  <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
</body>

</html>

templates/pages/contacto.html
{% extends '_base.html' %}
{% load static %}
{% load bootstrap_icons %}

{% block content %}
<div id="contact-margin" class="container">
  <h4 class="text-center">Página de Contacto</h4>
  <div>
    <p class="d-flex flex-wrap align-items-center justify-content-center contact-links text-center text-2s">Nuestro correo y télefono están siempre
      a
      disposición: <a class="mx-1 text-2s" href="mailto:wynandgroup@gmail.com"
        target="_blank">wynandgroup@gmail.com</a> | <button type="button" class="d-flex flex-wrap align-items-center btn ms-1">{% bs_icon 'whatsapp' %}<a href="https://wa.me/542284229093/?text=Hola, me llamo <> y quiero saber más sobre Wynand Group Propiedades." target="_blank">Contactar</a></button></p>
  </div>
  <hr>
  <p class="text-center text-2s">El suiguiente formulario necesita que inicie sesión en su cuenta de Google, para que
    pueda cargar imagenes.</p>
  <p class="contact-links text-center text-2s">Si no tiene una cuenta de Google puede crear una desde aqui: <a 
      href="https://www.google.com/intl/es/account/about/" target="_blank">Google</a></p>
  <div class="row g-3">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center">Publicar Propiedad</h5>
          <p class="card-text text-center text-2s">Complete este formulario para enviarnos todos los detalles de su
            propiedad y
            sus datos de
            contacto.</p>
          <ul class="list-group list-group-flush">
            <a class="btn" href="https://forms.gle/MA17AoFeA5fKnXFk6" target="_blank">Formulario</a>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/pages/detalles.html
{% extends '_base.html' %}
{% load static %}
{% load bootstrap_icons %}
{% load humanize %}

{% block content %}
<div id="main-margin-detalles" class="mx-4 row row-cols-1 row-cols-md-1">
  <div class="col p-1">
    <div class="card border-0">
      <div class="d-flex flex-row flex-wrap justify-content-center">
        {% for imagen in propiedad.imagen_set.all %}
        <div class="p-2 image-container">
          <img class="border" src="{{ imagen.imagen.url }}"
            alt="{{ img.imagen.url }}">
        </div>
        {% endfor %}
      </div>
      <div id="card-body-detalles" class="card-body">
        <ul class="list-group list-group-flush">
          <div class="d-flex flex-wrap align-items-center justify-content-evenly">
            <li class="list-group-item text-1s">${{ propiedad.precio|intcomma }}</li>
            {% if propiedad.numero_direccion %}
            <li class="list-group-item text-1s">{% bs_icon 'signpost-split' %}{{ propiedad.direccion.title }} - {{ propiedad.numero_direccion }}</li>
            {% else %}
            <li class="list-group-item text-1s">{% bs_icon 'signpost-split' %}{{ propiedad.direccion.title }}</li>
            {% endif %}
          </div>
          {% if propiedad.duracion_contrato or propiedad.expensas or propiedad.antiguedad or propiedad.metros_cuadrados %}
          <hr>
          <div class="d-flex flex-wrap align-items-center justify-content-evenly">
            {% if propiedad.metros_cuadrados %}
            <li class="list-group-item text-2s">{% bs_icon 'arrows-angle-expand' %}{{ propiedad.metros_cuadrados }}m²</li>
            {% endif %}
            {% if propiedad.duracion_contrato %}
            <li class="list-group-item text-2s">{% bs_icon 'calendar' %}Contrato - {{ propiedad.duracion_contrato }}</li>
            {% endif %}
            {% if propiedad.expensas %}
            <li class="list-group-item text-2s">{% bs_icon 'cash' %}Expensas - ${{ propiedad.expensas|intcomma }}</li>
            {% endif %}
            {% if propiedad.antiguedad %}
            <li class="list-group-item text-2s">{% bs_icon 'house-up' %}Año de Construcción - {{ propiedad.antiguedad }}</li>
            {% endif %}
          </div>
          {% endif %}
          {% if propiedad.ambientes or propiedad.habitaciones or propiedad.baños or propiedad.garage %}
          <hr>
          <div class="d-flex flex-wrap align-items-center justify-content-evenly">
            {% if propiedad.ambientes %}
            <li class="list-group-item text-2s">{% bs_icon 'door-open' %}Ambientes - {{ propiedad.ambientes }}</li>
            {% endif %}
            {% if propiedad.habitaciones %}
            <li class="list-group-item text-2s">{% bs_icon 'lamp' %}Habitaciones - {{ propiedad.habitaciones }}</li>
            {% endif %}
            {% if propiedad.baños %}
            <li class="list-group-item text-2s">{% bs_icon 'door-closed' %}Baños - {{ propiedad.baños }}</li>
            {% endif %}
            {% if propiedad.garage %}
            <li class="list-group-item">{% bs_icon 'car-front' %}Garage - {{ propiedad.garage }}</li>
            {% endif %}
          </div>
          {% endif %}
          {% if propiedad.niños or propiedad.mascotas %}
          <hr>
          <div class="d-flex flex-wrap align-items-center justify-content-evenly">
            {% if propiedad.niños %}
            <li class="list-group-item text-2s">{% bs_icon 'balloon' %}Niños - {{ propiedad.niños }}</li>
            {% endif %}
            {% if propiedad.mascotas %}
            <li class="list-group-item text-2s">{% bs_icon 'balloon-heart' %}Mascotas - {{ propiedad.mascotas }}</li>
            {% endif %}
          </div>
          {% endif %}
          <hr>
          <div class="d-flex flex-wrap align-items-center justify-content-evenly" style="padding-bottom: 8px;">
            <button type="button" class="d-flex flex-wrap align-items-center btn text-2s">{% bs_icon 'whatsapp' %}<a href="https://wa.me/542284229093/?text=Hola, me llamo <> y quiero saber más sobre la propiedad ubicada en <>." target="_blank">Contactar</a></button>
          </div>
        </ul>
      </div>
    </div>
  </div>
  {% if propiedad.info_extra %}
  <div class="col p-1  d-flex flex-wrap justify-content-center">
    <div class="card text-center border border-0">
      <div class="card-body px-2 border border-0">
        <h5 class="card-title text-1s">Información extra</h5>
        <p class="card-text text-2s">{{ propiedad.info_extra }}</p>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock content %}

templates/pages/propiedades.html
{% extends '_base.html' %}
{% load static %}
{% load bootstrap_icons %}
{% load humanize %}

{% block content %}
<nav class="filter-nav nav nav-pills flex-column flex-sm-row mx-4 justify-content-center">
  <a class="filter-link text-sm-center nav-link" data-categoria="Venta">En Venta</a>
  <a class="filter-link text-sm-center nav-link" data-categoria="Alquiler">En Alquiler</a>
  <a id="clean-filters" class="text-sm-center nav-link" href="{% url 'propiedades' %}">Limpiar filtros</a>
</nav>
<hr class="filter-hr">
<div id="main-margin" class="mx-4 row row-cols-1 row-cols-md-3 g-0 justify-content-evenly">
  <!--CARD START-->
  {% for propiedad in propiedades %}
  <div class="col m-2">
    <div {% if propiedad.destacado %} id="destacado" class="card-propiedad card" {% else %} class="card-propiedad card"
      {% endif %}>
      {% for imagen in propiedad.imagen_set.all %}
      {% if forloop.first %}
      <img src="{{ imagen.imagen.url }}" alt="">
      {% endif %}
      {% endfor %}
      <!--CARD BODY START-->
      <div class="card-body">
        <ul class="list-group list-group-flush">
          {% if propiedad.destacado %}
          <a id="btn-destacado" class="btn disabled" href="#" aria-disabled="true" tabindex="-1"
            role="button">Destacado</a>
          {% endif %}
          <div class="d-flex flex-wrap align-items-center justify-content-evenly">
            <li class="list-group-item text-2s">{{ propiedad.categoria }}</li>
            {% if propiedad.dolares %}
            <li class="list-group-item text-1s">USD {{ propiedad.precio|intcomma }}</li>
            {% else %}
            <li class="list-group-item text-1s">${{ propiedad.precio|intcomma }}</li>
            {% endif %}
            {% if propiedad.numero_direccion %}
            <li class="list-group-item text-1s">{% bs_icon 'signpost-split' %}{{ propiedad.direccion.title }} - {{ propiedad.numero_direccion }}</li>
            {% else %}
            <li class="list-group-item text-1s">{% bs_icon 'signpost-split' %}{{ propiedad.direccion.title }}</li>
            {% endif %}
          </div>
          {% if propiedad.ambientes or propiedad.habitaciones or propiedad.baños or propiedad.metros_cuadrados%}
          <hr>
          <div class="d-flex flex-wrap align-items-center justify-content-evenly" style="margin-bottom: 0.5rem;">
            {% if propiedad.metros_cuadrados %}
            <li class="list-group-item">{% bs_icon 'arrows-angle-expand' %}{{ propiedad.metros_cuadrados }}m²</li>
            {% endif %}
            {% if propiedad.ambientes %}
            <li class="list-group-item">{% bs_icon 'door-open' %}Ambientes - {{ propiedad.ambientes }}</li>
            {% endif %}
            {% if propiedad.habitaciones %}
            <li class="list-group-item">{% bs_icon 'lamp' %}Habitaciones - {{ propiedad.habitaciones }}</li>
            {% endif %}
            {% if propiedad.baños %}
            <li class="list-group-item">{% bs_icon 'door-closed' %}Baños - {{ propiedad.baños }}</li>
            {% endif %}
          </div>
          {% endif %}
          <a class="btn" href="{{ propiedad.get_absolute_url }}">+ Ver Más</a>
        </ul>
      </div>
      <!--CARD BODY END-->
    </div>
  </div>
  {% endfor %}
  <!--CARD END-->
</div>
{% endblock content %}